# Generated by Django 5.1.4 on 2024-12-26 16:01

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a JPEG or PNG image (max size: 2MB).', null=True, upload_to=authentication.models.profile_picture_path, validators=[authentication.models.validate_image_size]),
        ),
    ]
