# Generated by Django 5.1.4 on 2024-12-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('admin', 'Admin'), ('external', 'External Partner')], max_length=20),
        ),
    ]
