# Generated by Django 5.1.4 on 2025-01-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Software Engineering', 'Software Engineering'), ('Cyber Security', 'Cyber Security')], max_length=100, null=True),
        ),
    ]
