# Generated by Django 5.1.4 on 2025-01-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_collaboration_description_collaboration_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='channel_group',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
