# Generated by Django 5.1.4 on 2025-02-05 16:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_collaboration_channel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='channel_group',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
