# Generated by Django 5.1.4 on 2025-02-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_collaboration_channel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
