# Generated by Django 5.1.4 on 2025-02-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_collaboration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Enable email notifications about account activity'),
        ),
        migrations.AddField(
            model_name='user',
            name='file_updates',
            field=models.BooleanField(default=True, help_text='Receive notifications when shared files are modified'),
        ),
    ]
